<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit.runner.visualstudio">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="xunit.v3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../../src/MinimalBankSystem.Api/MinimalBankSystem.Api.csproj" />
    <ProjectReference Include="../../src/MinimalBankSystem.Application/MinimalBankSystem.Application.csproj" />
    <ProjectReference Include="../../src/MinimalBankSystem.Domain/MinimalBankSystem.Domain.csproj" />
    <ProjectReference Include="../../src/MinimalBankSystem.Infrastructure/MinimalBankSystem.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>
</Project>
