// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MinimalBankSystem.Infrastructure.Persistence;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MinimalBankSystem.Infrastructure.Migrations
{
    [DbContext(typeof(BankDbContext))]
    [Migration("20260815011202_AddProductAudit")]
    partial class AddProductAudit
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MinimalBankSystem.Domain.Auditing.AuditRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("audit_id");

                    b.Property<Guid>("ActorIdentifier")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_identifier");

                    b.Property<string>("ActorRole")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("actor_role");

                    b.Property<DateTimeOffset>("AuditTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("audit_time");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("text")
                        .HasColumnName("correlation_id");

                    b.Property<string>("FailureBusinessErrorCode")
                        .HasMaxLength(128)
                        .HasColumnType("text")
                        .HasColumnName("failure_business_error_code");

                    b.Property<string>("OperationIdentifier")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("text")
                        .HasColumnName("operation_identifier");

                    b.Property<string>("Result")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("result");

                    b.Property<string>("TargetIdentifier")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("text")
                        .HasColumnName("target_identifier");

                    b.HasKey("Id");

                    b.ToTable("audit_records", null, t =>
                        {
                            t.HasCheckConstraint("ck_audit_records_actor_role", "actor_role IN ('administrator', 'teller', 'viewer')");

                            t.HasCheckConstraint("ck_audit_records_failure_code", "(result = 'success' AND failure_business_error_code IS NULL) OR result = 'failure'");

                            t.HasCheckConstraint("ck_audit_records_result", "result IN ('success', 'failure')");
                        });
                });

            modelBuilder.Entity("MinimalBankSystem.Domain.Identity.Operator", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AuthorizationStateVersion")
                        .HasColumnType("integer")
                        .HasColumnName("authorization_state_version");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("NormalizedUserName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("text")
                        .HasColumnName("normalized_user_name");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("fixed_role");

                    b.Property<string>("SecurityStamp")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("security_stamp");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("state");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("text")
                        .HasColumnName("user_name");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("ix_operators_normalized_user_name");

                    b.ToTable("operators", null, t =>
                        {
                            t.HasCheckConstraint("ck_operators_fixed_role", "fixed_role IN ('administrator', 'teller', 'viewer')");

                            t.HasCheckConstraint("ck_operators_state", "state IN ('active', 'disabled')");
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
